[package]
name = "src-tauri"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
sdw_core = { path = "../core" }
database = { path = "../database" }
indexing = { path = "../indexing" }
automation = { path = "../automation" }
tauri = { version = "1.2", features = [ "updater", "dialog-all", "fs-all", "path-all", "custom-protocol"] }
serde = { version = "1.0", features = ["derive"] }
trash = "5.2.6"
serde_json = "1.0"
tokio = { version = "1.28", features = ["full"] }
uuid = { version = "1.4", features = ["v4"] }
chrono = "0.4"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
